name: Workflow lors d'un push

on: 
  push: 

jobs:
  mon-job: 
    runs-on: ubuntu-latest

    steps: 
      - name: Récupération de notre application
        uses: actions/checkout@v4

      - name: Installation des dépendances
        run: npm install

      - name: Build de l'application
        run: npm run build

      - name: Tests
        run: npm run test

  mon-2-job:
    runs-on: ubuntu-latest

    steps:
      - name: Étape 2
        run: echo "Étape 2 du second job"