name : Workflow lors d un push

on : push

jobs :
  mon-job : 
    runs-on : ubuntu-latest

    steps : 
      - name : Recuperation de notre application
        uses : actions/checkout@v4

      - name : Installation des dependences
        run : npm install

      - name : Build de l application
        run : npm run build

      - name : test
        run : npm run test